### ISSUE TITLE
Unable to make send api call with brand

### ISSUE THREAD

**Issue by sesopenko** [trycourier/courier-php#2]
The send api call doesn't support selecting a brand:  https://github.com/trycourier/courier-php/blob/main/src/Courier.php#L183

The client has to be updated to support a brand ID so that notifications can be sent without having to always use the default brand.

https://docs.courier.com/reference/send-api#sendmessage

**Comment by DannyDouglass** [comment]
@sesopenko thanks for reaching out! @tk26 just added `brand` support to the `sendNotification` method and our package has been updated: https://packagist.org/packages/trycourier/courier
