### ISSUE TITLE
Updating minimum PHP version

### ISSUE THREAD

**Issue by slashequip** [trycourier/courier-php#28]
Just wanted to get some insight on the current minimum version of PHP required in composer.

Is there a current reason for the requirement of `>=7.2`, the current minimum maintained version of PHP is `7.4` which is receiving security fixes until  28th November 2022.

See [support table](https://www.php.net/supported-versions.php) for more insight.

With your blessing it would be nice to upgrade that minimum to at least 7.4 for security, updates etc. You may have further insight into the current versioning that I do not of course!

**Comment by tk26** [comment]
I think it should be a totally right thing to move it to 7.4! No reason for >=7.2
